/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carbonCreditMarketPlaceSol from "./CarbonCreditMarketPlace.sol";
export type { carbonCreditMarketPlaceSol };
export type { CarbonCredit } from "./CarbonCredit";
